import { useState } from "react";
import { MovieCard } from "../movie-card/movie-card";
import { MovieView } from "../movie-view/movie-view";

export const MainView = () => {
    const [movies, setMovies] = useState([
        { "_id": { "$oid": "640f7ed735528f0b80b8c06c" }, "Title": "Silence of the Lambs", "Description": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.", "Genre": { "Name": "Thriller", "Description": "Thriller film, also known as a suspense film or suspense thriller, is a broad film, genre that involves excitement and suspence for the audience." }, "Director": { "Name": "Jonathan Demme", "Bio": "Robert Jonathan Demme was an American director, producer, and screenwriter.", "Birth": "1944", "Death": "2017" }, "ImagePath": "https://upload.wikimedia.org/wikipedia/sco/8/86/The_Silence_of_the_Lambs_poster.jpg", "Featured": true },
        { "_id": { "$oid": "640fed96b2d5936f3cb49cde" }, "Title": "The Lord of the Rings: The Return of the King", "Description": "Hobbits Frodo and Sam reach Mordor in their quest to destroy the one ring, while Aragorn leads the forces of good against Sauron's army at the stone city of Minas Tirith.", "Genre": { "Name": "Fantasy", "Description": "An imaginative fiction dependent for effect on strangeness of setting (such as other worlds or times) and of characters (such as supernatural or unnatural beings)." }, "Director": { "Name": "Peter Jackson", "Bio": "Sir Peter Robert Jackson is a New Zealand film director, screenwriter and producer. He is best known as the director, writer and producer of the Lord of the Rings trilogy and the Hobbit trilogy, both of which are adapted from the novels of the same name by J. R. R. Tolkien.", "Birth": "1961" }, "ImagePath": "https://upload.wikimedia.org/wikipedia/en/b/be/The_Lord_of_the_Rings_-_The_Return_of_the_King_%282003%29.jpg", "Featured": false },
        { "_id": { "$oid": "640ff0e2a00566aaab458c06" }, "Title": "The Hobbit: The Battle of the Five Armies", "Description": "Bilbo and company are forced to engage in a war against an array of combatants and keep the Lonely Mountain from falling into the hands of a rising darkness.", "Genre": { "Name": "Fantasy", "Description": "An imaginative fiction dependent for effect on strangeness of setting (such as other worlds or times) and of characters (such as supernatural or unnatural beings)." }, "Director": { "Name": "Peter Jackson", "Bio": "Sir Peter Robert Jackson is a New Zealand film director, screenwriter and producer. He is best known as the director, writer and producer of the Lord of the Rings trilogy and the Hobbit trilogy, both of which are adapted from the novels of the same name by J. R. R. Tolkien.", "Birth": "1961" }, "ImagePath": "https://upload.wikimedia.org/wikipedia/en/e/e7/The_Hobbit_-_The_Battle_of_the_Five_Armies.png", "Featured": false },
        { "_id": { "$oid": "640ff25d0f473e3f652aee26" }, "Title": "Star Wars: Episode IV - A New Hope", "Description": "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.", "Genre": { "Name": "Science Fiction", "Description": "Science Fiction is a fictionalized story wherein the setting and plot are centered around technology, time travel, outer space, or scientific principles, with or without the presence of aliens." }, "Director": { "Name": "George Lucas", "Bio": "George Walton Lucas Jr. is an American filmmaker. Lucas is best known for creating the Star Wars and Indiana Jones franchises and founding Lucasfilm, LucasArts, Industrial Light & Magic and THX. He served as chairman of Lucasfilm before selling it to The Walt Disney Company in 2012.", "Birth": "1944" }, "ImagePath": "https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg", "Featured": false },
        { "_id": { "$oid": "640ff326641a5db68a15b939" }, "Title": "Star Wars: Episode V - The Empire Strikes Back", "Description": "After the Rebels are overpowered by the Empire, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.", "Genre": { "Name": "Science Fiction", "Description": "Science Fiction is a fictionalized story wherein the setting and plot are centered around technology, time travel, outer space, or scientific principles, with or without the presence of aliens." }, "Director": { "Name": "George Lucas", "Bio": "George Walton Lucas Jr. is an American filmmaker. Lucas is best known for creating the Star Wars and Indiana Jones franchises and founding Lucasfilm, LucasArts, Industrial Light & Magic and THX. He served as chairman of Lucasfilm before selling it to The Walt Disney Company in 2012.", "Birth": "1944" }, "ImagePath": "https://upload.wikimedia.org/wikipedia/en/3/3f/The_Empire_Strikes_Back_%281980_film%29.jpg", "Featured": false },
        { "_id": { "$oid": "640ff43c6a31d1df4823dcf0" }, "Title": "Star Wars: Episode VI - Return of the Jedi", "Description": "After rescuing Han Solo from Jabba the Hutt, the Rebels attempt to destroy the second Death Star, while Luke struggles to help Darth Vader back from the dark side.", "Genre": { "Name": "Science Fiction", "Description": "Science Fiction is a fictionalized story wherein the setting and plot are centered around technology, time travel, outer space, or scientific principles, with or without the presence of aliens." }, "Director": { "Name": "George Lucas", "Bio": "George Walton Lucas Jr. is an American filmmaker. Lucas is best known for creating the Star Wars and Indiana Jones franchises and founding Lucasfilm, LucasArts, Industrial Light & Magic and THX. He served as chairman of Lucasfilm before selling it to The Walt Disney Company in 2012.", "Birth": "1944" }, "ImagePath": "https://upload.wikimedia.org/wikipedia/en/b/b2/ReturnOfTheJediPoster1983.jpg", "Featured": false },
        { "_id": { "$oid": "640ff68efee47ad1cec26ec5" }, "Title": "Jurassic Park", "Description": "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.", "Genre": { "Name": "Science Fiction", "Description": "Science Fiction is a fictionalized story wherein the setting and plot are centered around technology, time travel, outer space, or scientific principles, with or without the presence of aliens." }, "Director": { "Name": "Steven Spielberg", "Bio": "Steven Allan Spielberg is an American film director, writer and producer. A major figure of the New Hollywood era and pioneer of the modern blockbuster, he is the most commercially successful director of all time.", "Birth": "1946" }, "ImagePath": "https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg", "Featured": false },
        { "_id": { "$oid": "640ff7c059722c900a745154" }, "Title": "The 40-Year-Old Virgin", "Description": "Goaded by his buddies, a nerdy guy who's never \"done the deed\" only finds the pressure mounting when he meets a single mother.", "Genre": { "Name": "Comedy", "Description": "Comedy is a genre of film in which the main emphasis is on humor. These films are designed to make the audience laugh through amusement and most often work by exaggerating characteristics for humorous effect." }, "Director": { "Name": "Judd Apatow", "Bio": "Judd Apatow is an American producer, writer, director, actor and stand-up comedian.", "Birth": "1967" }, "ImagePath": "https://upload.wikimedia.org/wikipedia/en/4/43/40-Year-OldVirginMoviePoster.jpg", "Featured": false },
        { "_id": { "$oid": "640ff936f9adfea888335439" }, "Title": "E.T. the Extra-Terrestrial", "Description": "A troubled child summons the courage to help a friendly alien escape from Earth and return to his home planet.", "Genre": { "Name": "Science Fiction", "Description": "Science Fiction is a fictionalized story wherein the setting and plot are centered around technology, time travel, outer space, or scientific principles, with or without the presence of aliens." }, "Director": { "Name": "Steven Spielberg", "Bio": "Steven Allan Spielberg is an American film director, writer and producer. A major figure of the New Hollywood era and pioneer of the modern blockbuster, he is the most commercially successful director of all time.", "Birth": "1946" }, "ImagePath": "https://upload.wikimedia.org/wikipedia/en/6/66/E_t_the_extra_terrestrial_ver3.jpg", "Featured": false },
        { "_id": { "$oid": "640ffae8053da6a0ff81db82" }, "Title": "Indiana Jones and the Temple of Doom", "Description": "Indiana Jones is asked by desperate villagers to find a mystical stone and rescue their children from a Thuggee cult practicing child slavery, black magic, and ritual human sacrifice in honor of the goddess Kali.", "Genre": { "Name": "Action", "Description": "Movies in the action genre are fast-paced and include a lot of action like fight scenes, chase scenes, and slow-motion shots. They can feature superheroes, martial arts, or exciting stunts. These high-octane films are more about the execution of the plot rather than the plot itself." }, "Director": { "Name": "Steven Spielberg", "Bio": "Steven Allan Spielberg is an American film director, writer and producer. A major figure of the New Hollywood era and pioneer of the modern blockbuster, he is the most commercially successful director of all time.", "Birth": "1946" }, "ImagePath": "https://upload.wikimedia.org/wikipedia/en/1/10/Indiana_Jones_and_the_Temple_of_Doom_PosterB.jpg", "Featured": false }

    ]);

    const [selectedMovie, setSelectedMovie] = useState(null);

    if (selectedMovie) {
        return (
            <MovieView
                movie={selectedMovie}
                onBackClick={() => {
                    setSelectedMovie(null);
                }}
            />
        );
    }
    if (movies.length === 0) {
        return <div>The movie list is empty</div>;
    }

    return (
        <div>
            {movies.map((movie) => {
                return (
                    <MovieCard
                        key={movie._id}
                        movie={movie}
                        onMovieClick={(newSelectedMovie) => {
                            setSelectedMovie(newSelectedMovie);
                        }}
                    />
                );
            })}
        </div>
    );
};